### ISSUE TITLE
Solarized light is actually solarized dark

### ISSUE THREAD

**Issue by lryta** [chriskempson/base16-vim#104]
Hi Chriskempson,

The solarized-light version is not working as expected. When applied to vim, it shows solarized dark, the same as solarized-dark.vim. This issue appears in OSX 10.11.5 iTerm 2, 3.0.4, with Base16 solarized light scheme for terminal. My vim version is 7.4. My related settings are:
`colorscheme base16-solarized-light`
`set background=light`

The base16 series are awesome colorschemes. Thanks for your hard work :dancer:

**Comment by dkrmr** [comment]
Same here.

**Comment by chriskempson** [comment]
The Vim theme only sets the colours of the GUI. If you are using the terminal you'll have to use solarised light in your terminal to see any effect.

**Comment by lryta** [comment]
@chriskempson I am a little confused. Currently I'm using base16 solarized light theme in my iTerm2 terminal. However, when I apply solarized light vim theme to my vim, the output is still solarized dark. I assume some tricky little details get messed up.

@dkrmr Do you have the same problem under your settings? Even with base16 solarized theme for the terminal?

**Comment by dkrmr** [comment]
@lryta Well i made a little mistake, i actually use the base16-default theme not the solarized one. But the problem is still the same.
The theme for the terminal is base16-default-dark and for Vim it's base16-default-light.
Before the update, everything was working fine. The terminal was dark and when i opened Vim it was the light theme. Now i always have a dark Vim. Even with `background=light` or `colorscheme base16-default-light`

**Comment by chriskempson** [comment]
@dkrmr You can't use a dark terminal theme and a light vim theme anymore I'm afraid.

**Comment by dkrmr** [comment]
Oh... that's sad :(
Why ?

**Comment by sometoby** [comment]
Any news on this? I'm having the same problem as OP.

**Comment by minaguib** [comment]
This fixed it for me in .vimrc:

```
if has("gui_running")
  colorscheme base16-solarized-light
endif
```

Now vim GUI uses the right theme, and vim in terminal inherits terminal color scheme without causing the weird dark-light conflict

**Comment by lryta** [comment]
I tried @minaguib solution and it worked for me (the color was a little different but OK). Thanks!
