### ISSUE TITLE
Javascript operators are not colorized

### ISSUE THREAD

**Issue by keremc** [chriskempson/base16-vim#109]
Operators such as `of`, `void`, `delete`, `instanceof`, `in`, `typeof`, `new` are not colorized when using [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript) since they are assigned to the highlight group `jsOperator`, which is linked to `Operator`. Could you please override the `jsOperator` group (or maybe use a different color for the `Operator` group, otherwise you'll have to do this for every syntax script that uses the `Operator` group to highlight more than just `=`, `+`, `%`, etc.)?

**Comment by chriskempson** [comment]
I'd like the `=`, `+`, `%` operators to remain their current colour but agree that `of`, `void`, `delete`, `instanceof`, `in`, `typeof`, `new`. Would be nice to have an example JS file in https://github.com/chriskempson/base16-code-examples that covers all highlighting options so I can test with.

**Comment by keremc** [comment]
Here is an example:
```javascript
import {name as alternativeName} from 'module_name';

let string   = 'base16';
const symbol = Symbol('base16');
let number   = 0;
number       = 0.0;
let array    = new Array();
array        = ['chris', 85];
let hash     = {'test': 'test'};
let regexp   = /[abc]/;

function func() {
  return 'I am a function!';
}

// This is a comment
class Person {
  
  constructor(attributes = {}) {
    this.name = attributes['name'];
  }
  
  static greet() {
    return 'hello';
  }
}

let person1 = new Person({'name': 'Chris'});
console.log(Person.greet(), person1.name);
console.log(`another ${Person.greet()} ${person1.name}`);
```

**Comment by getkey** [comment]
Update on this? I can submit a PR if needed.

**Comment by chriskempson** [comment]
PR would be good 😄

**Comment by getkey** [comment]
Unfortunately since they are all part of the `jsOperator` group, we cannot highlight `delete`, `instanceof`, `typeof`, `void`, `new`, `in` and `of` separately from `!`, `|`, `&`, `+`, `-`, `<`, `>`, `=`, `%`,  `/`, `*`, `~` and `^`.

The only way would be to create a match group ourselves, but IMHO that's a bad idea.
