### ISSUE TITLE
Line numbers are colored green.

### ISSUE THREAD

**Issue by SliinQ** [chriskempson/base16-vim#110]
When trying to switch from the gruvbox colorscheme to base16-darktooth the line number column turned green. Is there a way to turn the green in gray without modifying the actual theme files?
I am using NeoVim if that makes a difference. 

Example: http://i.imgur.com/oW1Fw5K.png
My .vimrc file: http://pastebin.com/fGZHVszB
Here is my .Xresources: http://pastebin.com/b4TwLzFv
And I xrdb -merge the actual base16-darktooth-256.Xresources file
I am using URxvt with $TERM set to rxvt-unicode-256color

I have read through #24 and #25 but could not find a working solution in those except for actually changing the palette, however I would prefer a way to do this without modifying the palette.

**Comment by twizmwazin** [comment]
I can confirm that I am having this same issue, using neovim.

**Comment by twizmwazin** [comment]
Found a solution. Adding the following fixed this issue for me.

`
if has("termguicolors")
    set termguicolors
endif
`

This came from [this repository's readme](https://github.com/tyrannicaltoucan/vim-quantum).

**Comment by SliinQ** [comment]
@twizmwazin I am glad that fixed the problem for you, however for me it made an absolute mess of all the colors.

**Comment by twizmwazin** [comment]
It worked for me using gnome terminal. A (less lightweight) urxvt alternative is termite. It uses the same VTE backend as GNOME terminal, if you were interested in trying it out..

**Comment by binaryplease** [comment]
Hi, 

I'm having the same issue, This is what Neovim looks like:

![2017-03-05-165337_1904x1149_scrot](https://cloud.githubusercontent.com/assets/1719781/23588876/4c856e2a-01c4-11e7-80f0-b61207ae9ab6.png)

I'm using the base16-seti-ui theme installed with base16-shell on termite.

Termite Config:
https://ptpb.pw/rUyh

Vimrc/init.vim:
 https://ptpb.pw/IZDN

.Xressources:
 https://ptpb.pw/PGf9

Is this a configuration error or a bug?

**Comment by binaryplease** [comment]
There seem to be other people experiencing this issue with the seti theme ( @danielrs ), as detailed here:

https://github.com/chriskempson/base16-shell/issues/103#issuecomment-284587961
Updating everything, doesn't fix the problem. 

Here are all configs once again, in its newest version:

termite config: https://ptpb.pw/65w0
zshrc https://ptpb.pw/-BP2
init.vim https://ptpb.pw/H-hp
.Xressources https://ptpb.pw/i654

**Comment by danielrs** [comment]
I have the same issue, here's my screenshot with base16-seti:

![screenshot from 2017-03-07 14-06-35](https://cloud.githubusercontent.com/assets/1887507/23675575/67e6028e-033f-11e7-8f6f-3553e99cba28.png)

I tested some other color-schemes and they seem to be working fine.

**Comment by chriskempson** [comment]
Sounds like there might be a problem with the base16-seti scheme file?

**Comment by binaryplease** [comment]
@chriskempson Yes, but maybe not with the vim one. I have tried changing the theme for the terminal (termite) and vim, here are the results:

| Termite Theme | Vim Theme | Problem ?| 
|---|---|---|
| base16-default-dark |  base16-default-dark | no|
| base16-default-dark |base16-seti | no|
|base16-seti |  base16-default-dark |yes|
|base16-seti | base16-seti| yes|


I suspect the problem to be with the base16-seti theme file from base16-shell.

**Comment by chriskempson** [comment]
All the theme files should be identical apart from the colours. So the only way I can see this happening is if the colours are defined incorrectly in the scheme file. Perhaps base01 has been defined as green.

**Comment by danielrs** [comment]
@chriskempson [Here](https://github.com/chriskempson/base16-unclaimed-schemes/blob/master/seti.yaml) base01 was defined as [#8ec43d](http://www.colorhexa.com/8ec43d) (which is green). Do we have another source for the correct colors for seti?

**Comment by chriskempson** [comment]
I guess you'd have to contact the author of seti.

**Comment by chriskempson** [comment]
Actually just checked and this scheme lies in the unclaimed repo so it's one I ported from the old ruby builder. There's a possibility I made an mistake with the values.

**Comment by chriskempson** [comment]
Just checked the old builder. Seems I've not made a mistake as base01 was defined with the same hex value in the old scheme file too. Author is @HashBang173.

**Comment by HashBang173** [comment]
It looks like [#282A2B](http://www.color-hex.com/color/282a2b) might be a good color for base01. 

Color found from [here](https://github.com/trusktr/seti.vim/blob/master/colors/seti.vim#L15)

**Comment by binaryplease** [comment]
That looks good! Let me know when its been pulled in. Btw. @HashBang173  great theme, thanks for the work!

**Comment by beerygaz** [comment]
I'm trying to make use of base16 with MobaXterm as my terminal emulator connecting to a Ubuntu box.  I have the same ugly green issue until I set termguicolors but when I do, I lose my cursor.  The current line is highlighted but I can't see a cursor position on the current line.

If I run the base16 colortest I see blue lines, I'm not sure if this is related or not?
