### ISSUE TITLE
Vim colours not the same as website

### ISSUE THREAD

**Issue by deyvidm** [chriskempson/base16-vim#112]
The base16 website sample is on the left, and my version is on the right. 
Some of the colours aren't quite right. 
<img width="861" alt="screen shot 2016-09-22 at 12 39 12 pm" src="https://cloud.githubusercontent.com/assets/16841661/18757513/3a26c914-80c2-11e6-8034-0b3129303a3b.png">

I'm using iTerm2 and Console vim with the railscasts theme. I'm not using the 256 versions. 
Has anyone seen something similar? Solved already? 

Thanks for the help, it's appreciated.

**Comment by chriskempson** [comment]
Need to make a note of this somewhere but this is perfectly normal. The website is a styling guide of how the theme could look and should look but wont look as I'm yet to find an editor that lets me style everything the way I want it to look (without writing my own syntax highlighting definitions for every language).

**Comment by deyvidm** [comment]
Ah I understand. Then yes, it'd be wise to write a note that explains this.
