### ISSUE TITLE
IncSearch is broken again

### ISSUE THREAD

**Issue by ktchen14** [chriskempson/base16-vim#113]
Same issue as #37 in that IncSearch is set the same as Search:

``` vim
call <sid>hi("IncSearch", s:gui01, s:gui0A, s:cterm01, s:cterm0A, "none", "")
call <sid>hi("Search", s:gui01, s:gui0A, s:cterm01, s:cterm0A, "", "")
```

The fix referenced in that issue was:

``` diff
-call <sid>hi("IncSearch",     s:gui01, s:gui0A, s:cterm01, s:cterm0A, "none")
+call <sid>hi("IncSearch",     s:gui01, s:gui09, s:cterm01, s:cterm09, "none")
```

Which actually doesn't work that well since it doesn't fix terminal vim.

**Comment by poliquin** [comment]
I would fix this, but where exactly should the template be changed? `CONTRIBUTING.md` says not to submit pull requests here, but [chriskempson/base16-builder](https://github.com/chriskempson/base16-builder) says "This repository is deprecated."

**Comment by ktchen14** [comment]
Maybe we can get some clarification from @chriskempson

**Comment by chriskempson** [comment]
@poliquin This repo is the correct place to submit the PR as the vim template lives inside this repo (https://github.com/chriskempson/base16-vim/blob/master/templates/default.mustache).

**Comment by poliquin** [comment]
I just created pull request #129 to fix the template, but it seems base16-builder doesn't work with this template. I cannot update the actual scheme files.

@chriskempson can you clarify how the files under `colors/` should be created?

**Comment by chriskempson** [comment]
@poliquin There's a choice of builders at https://github.com/chriskempson/base16#builder-repositories
