### ISSUE TITLE
google-dark different (bad) colors in terminal than gui

### ISSUE THREAD

**Issue by Brottweiler** [chriskempson/base16-vim#114]
It seems like the google-dark theme I am using has some bad color choices, and I have some sample screenshots:

![](https://i.imgur.com/SkejUsd.png)

![](https://i.imgur.com/5sJqPpM.png)

In the first screenshot, you can see that when writing the git commit message, the selected line background has same color as the foreground, making it invisible.

Other than that, the green on blue and gray on orange is rather hard to read. Also green on red hurts eyes.

**Comment by chriskempson** [comment]
Have you tested if this is an issue with other colour schemes?

**Comment by Brottweiler** [comment]
Same thing happens with base16-flat, base16-eighties... While I wrote this, trying themes, it seems that regardless of theme the theme in vim doesn't change, just gvim. I use base16-google-dark colors for my terminal emulator from https://terminal.sexy/ (Termite), so maybe that is the issue actually.

**Comment by chriskempson** [comment]
In that case it sounds like an issue with your setup rather than something wrong with google-dark.

**Comment by Brottweiler** [comment]
Yeah most likely, will close for now unless this problem comes up again.

**Comment by Brottweiler** [comment]
FWIW, this is how it looks using badwolf colorscheme, not related to base16:

![](https://i.imgur.com/pRiHean.png)

But changing from one base16 theme to another doesn't seem to change much.

**Comment by Brottweiler** [comment]
Going to reopen because of my post above, any idea?

**Comment by Brottweiler** [comment]
I found a fix... here https://github.com/chriskempson/base16-vim/issues/110#issuecomment-257204974

Adding that to my `.vimrc` fixes the issue. Just compare:

- Without `termguicolors`: https://i.imgur.com/lzKBaEQ.png
- With `termguicolors`: https://i.imgur.com/XsTRKt6.png
