### ISSUE TITLE
Ruby string interpolation highlighting is broken

### ISSUE THREAD

**Issue by aaron-williamson** [chriskempson/base16-vim#115]
I noticed that there is an issue with the highlighting for string interpolation in ruby, visible in the ruby example [here](https://github.com/chriskempson/base16-code-examples/blob/master/ruby.rb).
Screenshot (actual): 
<img width="527" alt="screen shot 2016-10-03 at 5 17 48 pm" src="https://cloud.githubusercontent.com/assets/9038848/19057530/bba2c532-898d-11e6-917c-c94466b10035.png">

As you can see, the highlighting for `Person::greet` and the interpolated `"#{Person::greet}"` differs, which I don't believe is intended behaviour, as it is the same in the preview [here](https://chriskempson.github.io/base16/).
Screenshot (expected):
<img width="412" alt="screen shot 2016-10-03 at 5 22 42 pm" src="https://cloud.githubusercontent.com/assets/9038848/19057577/152ddff6-898e-11e6-885a-f863075803e7.png">

**Comment by chriskempson** [comment]
The preview is just an example of how it _should_ look in an editor. I've not yet found an editor that lets me theme it exactly as the preview looks so there will always be areas that do not match the preview I'm afraid.

**Comment by chriskempson** [comment]
See: https://github.com/chriskempson/base16-vim/issues/112#issuecomment-251110902

**Comment by aaron-williamson** [comment]
I think there was a bit of a miscommunication about what I meant, I've made a change (and can PR it as well if you agree) to fix what I was talking about. It was the fact that the interpolated code inside the ruby string was different inside the string compared to outside the string.
Before fix:
<img width="527" alt="screen shot 2016-10-03 at 5 17 48 pm" src="https://cloud.githubusercontent.com/assets/9038848/19057530/bba2c532-898d-11e6-917c-c94466b10035.png">
After fix:
<img width="527" alt="screen shot 2016-10-21 at 5 21 05 pm" src="https://cloud.githubusercontent.com/assets/9038848/19614476/ce2bf164-97b2-11e6-95b3-8b9e0e5e30e8.png">
As you can see, the `::greet` and `person1.name1` don't match inside the string and outside the string in the first image, but they do in the second. Let me know if you'd like me to PR this.

**Comment by chriskempson** [comment]
Oh sorry. I certainly misread this the first time around. Yep a PR would be great thanks 👍
