### ISSUE TITLE
Light Color Scheme Not Working

### ISSUE THREAD

**Issue by F1LT3R** [chriskempson/base16-vim#116]
When I change to `background=light` I would have expected the light version of the color scheme to be used, but this is not the case, even restarting VIM.

How would I go about activating the light version of any given color scheme?

**Comment by chriskempson** [comment]
By using the light version of the theme e.g. base16-default-light.vim

**Comment by F1LT3R** [comment]
Ok thanks @chriskempson, I didn't realize it was that simple.

It appears that there are no light versions of some themes. I'm an avid user of "Flat". I found the non-existence of the light scheme quite surprising as I know it exists in other Base16 repos.

![screen shot 2016-10-12 at 7 34 32 am](https://cloud.githubusercontent.com/assets/1218446/19308594/6dee16ee-904e-11e6-94c0-571be0bb5df8.png)

**Comment by exchgr** [comment]
Are there any plans to reinstate the light versions of themes such as `bright` or `flat`?

**Comment by chriskempson** [comment]
Sure, if they are requested: https://github.com/chriskempson/base16/issues/42

**Comment by exchgr** [comment]
@chriskempson great, thanks!
