### ISSUE TITLE
I always get very strange issue with colours when I try and apply the theme

### ISSUE THREAD

**Issue by nikitavoloboev** [chriskempson/base16-vim#121]
This is how my vim looks like : 

![2016-10-24 at 21 46](https://cloud.githubusercontent.com/assets/6391776/19661304/79c0bb9a-9a33-11e6-99ad-ca11ae321f59.png)

I just added this line : 

``` Bash
colorscheme base16-darktooth
```

Why is that?

**Comment by Brottweiler** [comment]
I think you're having the same issue as me. https://github.com/chriskempson/base16-vim/issues/114

**Comment by Brottweiler** [comment]
Can you try this? https://github.com/chriskempson/base16-vim/issues/110#issuecomment-257204974
