### ISSUE TITLE
What is the default theme that is used when downloading base16-vim and booting up in dark mode

### ISSUE THREAD

**Issue by nikitavoloboev** [chriskempson/base16-vim#122]
I am talking about this theme : 

![2016-10-24 at 21 52](https://cloud.githubusercontent.com/assets/6391776/19661484/352cb744-9a34-11e6-8275-2896ca5acf6b.png)

I quite like it but some things are really too bright and I would love to change it. For example dim the line numbers, dim the status bar yellow parts. How can I go about changing these things?

Thank you.

**Comment by chriskempson** [comment]
That looks like the default Vim theme to me and not a base16 theme I'm afraid.
