### ISSUE TITLE
Cursor disappears on :%s/foo/bar/gc

### ISSUE THREAD

**Issue by nerfologist** [chriskempson/base16-vim#124]
Hello, let me provide you with some information about my current setup:

- Operating system: macOS 10.12.1 (16B2555)
- Terminal emulator: Terminal.app Version 2.7.1 (387)
- Terminal emulator theme: [base16-materia (16 colors)](https://github.com/vbwx/base16-terminal-app/blob/master/profiles/Materia.terminal) from [base16-terminal-app](https://github.com/vbwx/base16-terminal-app)
- vim colorscheme: [base16-materia](https://github.com/chriskempson/base16-vim/blob/master/colors/base16-materia.vim) from [base16-vim](https://github.com/chriskempson/base16-vim)

Configuration parameters: `set hlsearch`

When substituting file-wide, vim stops to let you confirm the substitution on every matched word. Unfortunately, in this case the cursor is not visible (so you can't tell which word you're substituting).

Here's a gif of the issue:
![cursor issue](http://i.giphy.com/l2JhOoJJKcSJ09dxS.gif)

**Comment by nerfologist** [comment]
On further investigation, this seems to be unrelated with the colorscheme, as I was able to reproduce the very same behaviour even without the base16-materia colorscheme applied.

**Comment by ktchen14** [comment]
I think this issue was resolved per issue #113 and #129.

**Comment by nerfologist** [comment]
I confirm this was fixed by #129. Thanks!
