### ISSUE TITLE
base16-eighties

### ISSUE THREAD

**Issue by alanwei0** [chriskempson/base16-vim#127]
i use base16-eighties in vim with iterm2, but i found that the comments color is so dark, i can hardly see it especially for a comment between normal white color codes, can you make the color lighter?
 
<img width="756" alt="screen shot 2016-12-07 at 9 58 37 am" src="https://cloud.githubusercontent.com/assets/3991105/20951916/c2dcb16a-bc63-11e6-86d5-ed295b8fcf31.png">

now i change the minimum contrast setting of iterm2 to the center, then the color looks better.

<img width="817" alt="screen shot 2016-12-07 at 10 06 09 am" src="https://cloud.githubusercontent.com/assets/3991105/20952109/032879b0-bc65-11e6-8904-1598708eea4b.png">

my env: 
macbook pro
iterm2 with base16-eighties-256
neovim with termguicolors(true color)

thank you!

**Comment by chriskempson** [comment]
Thanks for submitting this issue. However, I'm going to have to close it as it should be asked on https://github.com/chriskempson/base16 as this kind of change would affect all software that makes use of base16 eighties and not just vim.
