### ISSUE TITLE
Making use of bold and italic

### ISSUE THREAD

**Issue by rafaeln** [chriskempson/base16-vim#128]
Colorschemes like [seoul256](https://github.com/junegunn/seoul256.vim) give htmlItalic and htmlBold the attributes italic and bold, respectively. Base16 colorschemes don't. Maybe there's a design reason for that, but if other users like me prefer to see italic and bold instead of meaningless colors whenever they're editing markdown text, they can change the colorschemes manually thus:

```bash
cd base16-vim/colors
sed -ri '/Italic/ s/^([^,]*,){5} "(none)?/\1 "italic/' *vim
sed -ri '/Bold/ s/^([^,]*,){5} "(none)?/\1 "bold/' *vim    
```

**Comment by chriskempson** [comment]
This needs to be raised in https://github.com/chriskempson/base16 as this design change would affect more than just vim e.g. textmate and so on.

**Comment by rafaeln** [comment]
ok!
