### ISSUE TITLE
CursorLineNr

### ISSUE THREAD

**Issue by dawikur** [chriskempson/base16-vim#130]
I have found that making `CursorLineNr` different from `LineNr` greatly increases readability and search for current line.

![image](https://cloud.githubusercontent.com/assets/11866902/21507651/865ba8a0-cc7a-11e6-8b0f-7fa360fffe55.png) ![image](https://cloud.githubusercontent.com/assets/11866902/21507661/a7261354-cc7a-11e6-8e42-3348b4758626.png)

and looks great :)

using the opportunity, @chriskempson are you open to make this `colorscheme` more flexible?  There are opened issues (like #68, #128), I would love to change few settings. Are you open to parameter scheme?

I am also using [rainbow](https://github.com/luochen1990/rainbow), [easymotion](https://github.com/easymotion/vim-easymotion), etc. It would be great to have support 'out-of-the-box' for all those  plugins.

**Comment by chriskempson** [comment]
Yeah it's a nice idea adding some sort of highlighting to CursorLineNr thanks. As the colours of Base16 are generally used for code syntax highlighting and the grayscale for UI elements I've just lightened the text which seems to be just as effective as colouring it.
