### ISSUE TITLE
Improve brace colors

### ISSUE THREAD

**Issue by namjul** [chriskempson/base16-vim#131]
In base16 the cursor-color hovering a brace has the same color as the background.
This has an annoying effect when selected text.

base16-default-dark (i sometime lose focus on where my cursor is)
![out3](https://cloud.githubusercontent.com/assets/328836/21650159/5fda26ea-d2a4-11e6-8c43-8312a8722027.gif)

This is how it works in gruvbox
gruvbox
![out](https://cloud.githubusercontent.com/assets/328836/21650157/5de522a4-d2a4-11e6-9db8-7030bf5a3436.gif)

**Comment by BonarBeavis** [comment]
A workaround:
```
let loaded_matchparen = 1
```
This just disables the matching braces highlight.
