### ISSUE TITLE
Statement highlight should use base0e

### ISSUE THREAD

**Issue by tmccombs** [chriskempson/base16-vim#138]
According to http://chriskempson.com/projects/base16/ base0e should be used for Keywords, and the Statement highlight is used for things like `if`, `for`, `while`, `let`, etc. which are more like keywords than variables, and it is strange for those keywords to be highlighted the same as variables.

**Comment by chriskempson** [comment]
Variables should appear red, statements as purple. Depending on which editor you are using and which language you are editing this may not be the case due to various limitations.

**Comment by tmccombs** [comment]
```vim
call <sid>hi("Identifier",   s:gui08, "", s:cterm08, "", "none", "")
...
call <sid>hi("Statement",    s:gui08, "", s:cterm08, "", "", "")
```

Identifier and Statement are almost the same. When I edit .vim files, both the statement keywords and variables in declarations or red. So for example in `let some_var="something"` both `let` and `some_var` are red.

> this may not be the case due to various limitations
could you explain the limitations or point me to some documenetation?

**Comment by chriskempson** [comment]
The limitations occur when you're writing a theme file and trying to colour syntax elements and find that some elements can't be coloured separately to other elements. In the case of Vim I believe this can be remedied by writing syntax files but that is beyond the scope of this project. I've done my best to colour things as they should be but I did have to make compromises.

**Comment by chriskempson** [comment]
By the way, Vim does not see "let" as an identifier. It's type is "vimLet".

**Comment by tmccombs** [comment]
Right, and vimLet is aliased to vimCommand which is aliased to Statement. And the variable after the let is seen as vimVar which has a highlight alias of Identifier (from the syntax file for vim included with nvim anyway).

**Comment by chriskempson** [comment]
That's right yes. So it would be possible to colour "vimLet" differently and would probably be a good idea to do so but this is now a conversation about improving the highlighting of Vim syntax.  Changing something as general as the statement highlight will affect other languages.

**Comment by tmccombs** [comment]
I was going off of a combination of the vim documentation:

```
	*Statement	any statement
	 Conditional	if, then, else, endif, switch, etc.
	 Repeat		for, do, while, etc.
	 Label		case, default, etc.
	 Operator	"sizeof", "+", "*", etc.
	 Keyword	any other keyword
	 Exception	try, catch, throw
```
 and the base16 home page:
```
base08 - Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base0E - Keywords, Storage, Selector, Markup Italic, Diff Changed
```
which seems to me like Statement fits better with base0E (with the exception of operators).  That said the only place I have run into it so far is with vim syntax.

**Comment by chriskempson** [comment]
Perhaps the documentation should change then? The documentation came after the theme so the theme should be considered correct. In fact the Textmate theme more so than the Vim theme since that came first 😄

**Comment by tmccombs** [comment]
hmmm, looking at some other languages it seems that Statement isn't used very consistently at all. I'll close this.
