### ISSUE TITLE
Base16 themes messed up vim colors

### ISSUE THREAD

**Issue by enkeyz** [chriskempson/base16-vim#145]
Hello guys!
So I installed base16 colorschemes, and tried some colors. Here's the result:
![screenshot_20170604_104509](https://cloud.githubusercontent.com/assets/17646853/26760205/e5b12220-4912-11e7-9b73-a560f6aaea10.png)

My config files:
vimrc: https://pastebin.com/uZfM4tSB
Xresources: https://pastebin.com/ZhsSRQtC

Any possible solution?

**Comment by andreyorst** [comment]
Isn't it https://github.com/chriskempson/base16-vim#green-line-numbers problem?
