### ISSUE TITLE
Highlight color is not set for new QuickFixLine highlight group

### ISSUE THREAD

**Issue by beyondmarc** [chriskempson/base16-vim#147]
After [this patch](https://github.com/vim/vim/commit/2102035488e80ef6fd5038ed15d21672712ba0f6) in vim 8, there's a new highlight group, namely QuickFixLine, to define the color of the current line in the Quickfix window.

I'm using the monokai colorscheme, and if the QuickFixLine highlighting is not set, it defaults to a cyan background that makes the line unreadable. A slightly darker or lighter background shade (from regular vim background color) should make it both readable and still visible.

**Comment by chriskempson** [comment]
Sounds like this should use base for the colour? e.g. `call <sid>hi("QuickFixLine",    "", s:gui01, "", s:cterm01, "none", "")`.

**Comment by beyondmarc** [comment]
The base color works :)

**Comment by beyondmarc** [comment]
Looks good to me! :)

**Comment by chriskempson** [comment]
Great, have pushed this fix and updated the output. Thanks.

**Comment by beyondmarc** [comment]
Awesome, thanks!
