### ISSUE TITLE
Search highlight hard to read

### ISSUE THREAD

**Issue by afflux** [chriskempson/base16-vim#150]
I have a similar issue to #75 with the `Search` highlight on flat:

![image](https://user-images.githubusercontent.com/768184/27801833-7ccb301e-6020-11e7-9c94-6cca54371392.png)

But it's very hard to read in other themes (e.g. solarized-dark) as well.

Changing the foreground colors to `gui01` / `cterm01` fixes the issue for me:

```diff
--- a/.vim/colors/base16-solarized-dark.vim
+++ b/.vim/colors/base16-solarized-dark.vim
@@ -128,7 +128,7 @@ call <sid>hi("MatchParen",    "", s:gui03, "", s:cterm03,  "", "")
 call <sid>hi("ModeMsg",       s:gui0B, "", s:cterm0B, "", "", "")
 call <sid>hi("MoreMsg",       s:gui0B, "", s:cterm0B, "", "", "")
 call <sid>hi("Question",      s:gui0D, "", s:cterm0D, "", "", "")
-call <sid>hi("Search",        s:gui03, s:gui0A, s:cterm03, s:cterm0A,  "", "")
+call <sid>hi("Search",        s:gui01, s:gui0A, s:cterm01, s:cterm0A,  "", "")
 call <sid>hi("SpecialKey",    s:gui03, "", s:cterm03, "", "", "")
 call <sid>hi("TooLong",       s:gui08, "", s:cterm08, "", "", "")
 call <sid>hi("Underlined",    s:gui08, "", s:cterm08, "", "", "")
```

**Comment by chriskempson** [comment]
Do you want to submit this a PR or would you like me to apply the fix for you?

**Comment by afflux** [comment]
I'd appreciate it if you could apply the change, as I don't have the base16 builder set up on my system.
