### ISSUE TITLE
distribute with Vim?

### ISSUE THREAD

**Issue by chrisbra** [chriskempson/base16-vim#153]
there is an [issue](https://github.com/vim/vim/issues/1665) open in the vim repository, to distribute more colorschemes with Vim. Would you kindly give your permission to distribute the base16-default colorscheme with Vim?

**Comment by chriskempson** [comment]
Absolutely.

**Comment by chrisbra** [comment]
Great.

Well, I can collect your file and send it to Bram, or you can do it. I would prefer if you can do it, since you know obviously best, when it is kind of stable enough and of course you will know when to send updated themes to Bram for inclusion. If you would like to do it mention that this is for issue 1665 to fix it. thanks!

**Comment by chrisbra** [comment]
closing, according to chriskempson/vim-tomorrow-theme/issues/48 this can be closed and is not suitable for Vim. Thanks anyhow.
