### ISSUE TITLE
Generated coloscheme has invalid g:colors_name

### ISSUE THREAD

**Issue by avanzzzi** [chriskempson/base16-vim#157]
After an update, this message started to pop while opening vim:
```
$ vim 
Error detected while processing /usr/share/vim/vim80/syntax/synload.vim:
line   19:
E185: Cannot find color scheme 'base16-'
```
The source of problem is the variable colors_name, it's incomplete in the colorscheme output.
```
$ grep colors_name base16-monokai.vim 
let g:colors_name = "base16-"
```
Reverting to an older version (2d991f14 for instance) gives the right output, and the error disappers:
```
$ git checkout 2d991f1
HEAD is now at 2d991f1... Updates output
$ grep colors_name base16-monokai.vim 
let g:colors_name = "base16-monokai"
```

**Comment by bmedicke** [comment]
Had the same problem, thanks for the hint! For those using vim-plug you can pin the previous commit for now with `Plug 'chriskempson/base16-vim', {'commit': '2d991f1'}`.

**Comment by marconett** [comment]
Forked and reverted: https://github.com/marconett/base16-vim

**Comment by chriskempson** [comment]
Sorry about that, should be fixed now

**Comment by avanzzzi** [comment]
Fixed, thanks!
