### ISSUE TITLE
Background color is absolutely black, not like the screenshot

### ISSUE THREAD

**Issue by khashf** [chriskempson/base16-vim#170]
- [x] I have carefully read and followed the Installation section of the README
- [x] I have searched through the closed issues to see if there is an existing solution for my issue

### Issue Description

The background is incorrectly very black, and is not the intended color like in the screenshot in README.md

### Screenshot:
![image](https://user-images.githubusercontent.com/6059347/34660655-d6d20f6c-f3f8-11e7-8312-d142b72ded28.png)

  
### Terminal Emulator Info

Terminal emulator(s) and their version(s) used, if applicable: `gnome-terminal`

### Output From `vim --version`

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     -tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
-clientserver    +iconv           +packages        -toolbar
-clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             -perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            -ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xsmp
+emacs_tags      -mouseshape      +startuptime     -xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    -xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm    
```

**Comment by chriskempson** [comment]
How are you applying the colour scheme to gnome-terminal?

**Comment by khashf** [comment]
This is screenshot of my color scheme applied gnome-terminal (default profile), .vimrc, and how my vim appears.
This also shows my result of running the colortest script from the [base16-shell repo](https://github.com/chriskempson/base16-shell)

![image](https://user-images.githubusercontent.com/6059347/34699697-ae766a4a-f493-11e7-9823-cbe3ec1b8867.png)

**Comment by khashf** [comment]
Default gnome-terminal profile with dark background:
![image](https://user-images.githubusercontent.com/6059347/34699811-4eeb7394-f494-11e7-876e-2113bcd18ff9.png)

**Comment by khashf** [comment]
More screenshot:

Here some keywords are not highlighted, too.

![image](https://user-images.githubusercontent.com/6059347/34701715-8e3e9e18-f49e-11e7-8130-81c52302fd22.png)

My installed plugin:
```
[submodule "dotbot"]
	path = dotbot
	url = https://github.com/anishathalye/dotbot
[submodule "vim/bundle/gist-vim"]
	path = vim/bundle/gist-vim
	url = https://github.com/mattn/gist-vim.git
[submodule "vim/bundle/vim-pathogen"]
	path = vim/bundle/vim-pathogen
	url = https://github.com/tpope/vim-pathogen.git
[submodule "vim/bundle/webapi-vim"]
	path = vim/bundle/webapi-vim
	url = https://github.com/mattn/webapi-vim
[submodule "vim/bundle/vim-colors-solarized"]
	path = vim/bundle/vim-colors-solarized
	url = git://github.com/altercation/vim-colors-solarized.git
[submodule "vim/bundle/vim-one"]
	path = vim/bundle/vim-one
	url = https://github.com/rakr/vim-one.git
[submodule "vim/bundle/onedark.vim"]
	path = vim/bundle/onedark.vim
	url = https://github.com/joshdick/onedark.vim.git
[submodule "vim/bundle/vim-polyglot"]
	path = vim/bundle/vim-polyglot
	url = https://github.com/sheerun/vim-polyglot.git
[submodule "vim/bundle/base16-vim"]
	path = vim/bundle/base16-vim
	url = https://github.com/chriskempson/base16-vim.git
```

**Comment by chriskempson** [comment]
You're not colouring your terminal. A Vim theme cannot do this for you. You should use base16-shell to do this. 

As for the keywords that are not highlighted. Please read the note in the screenshot you provided 😉

**Comment by khashf** [comment]
**Confirm! It works after installing base16-shell as advised!**  Thank you so much! :+1: 

* About the syntax, would the [vim-polygon](https://github.com/sheerun/vim-polyglot) plugin be sufficient enough for improving syntax lexing and parsing? Would it conflict with other language-specific syntax improving plugins?

This issue reminds me of Ethan Schoonover's Solarized theme's README. Too bad I couldn't recall in time. 

> If you are going to use Solarized in Terminal mode (i.e. not in a GUI version like gvim or macvim), please please please consider setting your terminal emulator's colorscheme to used the Solarized palette.

> If you use Solarized without these colors, Solarized will need to be told to degrade its colorscheme to a set compatible with the limited 256 terminal palette (whereas by using the terminal's 16 ansi color values, you can set the correct, specific values for the Solarized palette).
> 
> If you do use the custom terminal colors, solarized.vim should work out of the box for you. If you are using a terminal emulator that supports 256 colors and don't want to use the custom Solarized terminal colors, you will need to use the degraded 256 colorscheme. To do so, simply add the following line before the colorscheme solarized line
