### ISSUE TITLE
Colors in MacVim and Terminal Vim

### ISSUE THREAD

**Issue by felixjung** [chriskempson/base16-vim#35]
Hi,

after a lot of pain and suffering, I managed to setup colours for Vim and Base-16 (Ocean Dark) in Terminal. However, compared to the MacVim version, Base16 Ocean Dark still looks off not only in Terminal Vim but in the Terminal overall (I'm using iTerm). Here are two screenshots of MacVim (upper) and Terminal Vim (lower):
![screen shot 2014-03-07 at 09 35 50](https://f.cloud.github.com/assets/265947/2355119/89f51076-a5d3-11e3-96e5-5310c40a47fc.png)

![screen shot 2014-03-07 at 09 33 23](https://f.cloud.github.com/assets/265947/2355093/284e76aa-a5d3-11e3-8178-3ac8d1d045cc.png)

The iTerm colours 'pop' way less and thus have less contrast and are less readable. Also note how the file encoding in the status bar has a dark background and light foreground colour in MacVim, but a light grey background and slightly less grey foreground in the Terminal. The Terminal, again, is less readable. I've recently played with centralising my dotfiles à la dotfiles.github.io. After that I also noticed that the yellow colour had turned orange in Terminal Vim. Since rearranging my dotfiles involved cloning all related repos again and you have made some amendments to the color schemes recently, I was wondering whether there might be some relation?

I have installed the base16-ocean.dark.256 theme in iTerm and have installed the Base16 shell and load it in my .zshrc:
```bash
# Base16 shell
BASE16_SCHEME="ocean"
BASE16_SHELL="$HOME/.config/base16-shell/base16-$BASE16_SCHEME.dark.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL
```
Here are the theme related parts from my .vimrc:
```
" Configure UI {
  set term=screen-256color
  set t_Co=256
  set background=dark
  let base16colorspace=256        " Access colors present in 256 colorspace
  colorscheme base16-ocean
  set nofoldenable                " disable code folding
" }
```
My Terminal is set to 'screen-256color'. I'm using MacVim/Vim 7.4 and iTerm 1.0.0.20140112.

Any ideas? I really appreciate the help!

**Comment by lencioni** [comment]
> I've just raised the issue on iTerm2's issue tracker: https://code.google.com/p/iterm2/issues/detail?id=3298

It looks like the iTerm2 issue tracker has been moved. The issue you referenced now seems to be at https://gitlab.com/gnachman/iterm2/issues/3298

I was using iTerm Build 2.1.1 with base16-shell and was seeing this issue. The colors were consistent between the shell and Vim, FWIW. Here's terminal Vim on the left and MacVim on the right:

![screen shot 2015-05-24 at 2 27 50 pm](https://cloud.githubusercontent.com/assets/195534/7789753/58f163de-0221-11e5-832a-01b5355f13e6.png)

I was able to resolve this by updating to the latest nightly iTerm2 (Build 2.9.20150523-nightly).

**Comment by yuejinzhao** [comment]
Sorry, but  I still have the problem of **green line** after change the Terminal theme to **Base 16 Tomorrow Dark** and 
I'm using gnome-terminal
Here is my screenshot
![2015-11-14 16-18-35](https://cloud.githubusercontent.com/assets/12369065/11162764/74737cc0-8aeb-11e5-976f-e35065d465e0.png)

**Comment by dylanscott** [comment]
If you don't want to be on a nightly iTerm 2 build (fix still isn't on stable), you can tweak the theme to display correctly. I went ahead and created a version for the [ocean theme](https://gist.github.com/dylanscott/f9a57d1bc5a4a9c7d919). You can generate the vim and iterm2 files using the [base16-builder](https://github.com/chriskempson/base16-builder) repo.

If you want to do the same thing with a different color scheme, you can use the Digital Color Meter app (built in to OS X), set it to "Display in Generic RGB" and grab the colors using the dropper on the [base16](https://chriskempson.github.io/base16/) site.

**Comment by brianyang** [comment]
i just grabbed night and solved this same issue. for anybody coming to this thread..
