### ISSUE TITLE
Background color goes wrong

### ISSUE THREAD

**Issue by Axiol** [chriskempson/base16-vim#55]
I just installed Base16 for my Vim config on OS X in stock term and when I activate the Ocean variant in dark, the background color isn't the good one. Seems like it's the same as the one for the comments.

![capture d ecran 2014-10-18 a 20 59 27](https://cloud.githubusercontent.com/assets/578111/4690765/439e7ad6-56f9-11e4-94dc-e83915c0babf.png)

![capture d ecran 2014-10-18 a 21 01 48](https://cloud.githubusercontent.com/assets/578111/4690767/4a1a43ae-56f9-11e4-9b0d-5adbb2ac6e62.png)

Maybe I've done something wrong ?

**Comment by nicksparks** [comment]
i my case i just  forget to close the iterm, tmux and vim  and run it again 
so i reload with config

part of my .vimrc:

```
let base16colorspace=256
set background=dark
colorscheme base16-eighties
```
part of my .zshrc:

```
BASE16_SHELL="$HOME/.config/base16-shell/base16-eighties.dark.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL
```
