### ISSUE TITLE
GitGutter background looks funny

### ISSUE THREAD

**Issue by sondr3** [chriskempson/base16-vim#59]
I'm having some problems with using the solarized-light version of your theme because the GitGutter have the same background as the cursor line has, this looks pretty ugly.

Here's a screenshot without clearing the GitGutter settings:
![screenshot 2014-12-21 20 43 24](https://cloud.githubusercontent.com/assets/2280539/5519398/285fcdde-8952-11e4-99a9-c49fa7f4ed67.png)

And here when I clear it:
![screenshot 2014-12-21 20 41 47](https://cloud.githubusercontent.com/assets/2280539/5519399/2bd676c0-8952-11e4-86c8-b0306a5a5b5d.png)

I'm running the latest Iterm2 nightly as well as solarized-light with 256 support from the base16-shell script in my `.zshrc` file. I've fixed it myself now but I'm just curious if this is intended or some sort of bug?

**Comment by chriskempson** [comment]
It should have the same background as the line numbers (which would be the same colour as the highlighted line). For some reason your line numbers don't have any background colours.

**Comment by sondr3** [comment]
Yeah, not really sure what's up with it. Just installed via VimPlug and it looked kinda funny some places.

**Comment by pickfire** [comment]
Yeah, it looks a bit funny not only on the gitgutter but colorcolumn is a bit weird too. The color looks very different when comparing side by side.

![term](https://cloud.githubusercontent.com/assets/4687791/6202945/bd90ba5c-b540-11e4-86f4-94a0bccec9d8.png)

**Comment by pickfire** [comment]
I think this has something to do with `:highlight SignColumn` as it shows:
```
SignColumn     xxx term=standout ctermfg=8 ctermbg=18 guifg=#657b83
                   guibg=#073642
```
