### ISSUE TITLE
Comments are white instead of grey in iTerm2

### ISSUE THREAD

**Issue by nicknikolov** [chriskempson/base16-vim#60]
Hi

iTerm 2:
![screen shot 2015-01-22 at 12 36 07](https://cloud.githubusercontent.com/assets/1440420/5855756/9284ec4a-a233-11e4-8f8d-04f4ed1f01d0.png)

MacVim
![screen shot 2015-01-22 at 12 37 08](https://cloud.githubusercontent.com/assets/1440420/5855768/a8985fe4-a233-11e4-99f4-386dc08040b7.png)

Same happens in other languages.
Using Build 2.9.20150108-nightly with xterm-new terminal emulation

My vimrc
colorscheme base16-twilight
set background=dark

What am I missing?

Thanks
Nick

**Comment by amaltson** [comment]
I'm having the exact same issue. I tried using the shell colours thinking that might fix it but still see white :cry:

**Comment by xHN35RQ** [comment]
did you try `let base16colorspace=256` before `colorscheme base16-twilight` ?
