### ISSUE TITLE
Some colors are not showing

### ISSUE THREAD

**Issue by indiesquidge** [chriskempson/base16-vim#61]
So I know a lot of people are upset that the colors don't show _exactly_ the same as the examples you give, but I realize that different apps are going to display different palates.

However, I am curious as to why some colors just don't show up all together, or show up as a completely wrong color. I am currently using the `base16-default.dark.itermcolors` and using Vim as my editor. Here's a screencap of what my colors look like:

![screen shot 2015-01-27 at 10 04 31 am](https://cloud.githubusercontent.com/assets/3409645/5922906/8ae771c4-a60c-11e4-8615-658d1e6fef43.png)

vs. the example (again, ignoring contrast and saturation differences):
![screen shot 2015-01-27 at 10 09 21 am](https://cloud.githubusercontent.com/assets/3409645/5922916/98c7b39e-a60c-11e4-90bb-419ce1fb9692.png)

**Comment by chriskempson** [comment]
I'm afraid the example is just example. I've not yet found an editor that opens up enough syntax highlighting options to achieve exactly what I'd like. Plus since all editors have their own methods of syntax highlighting they will all look a little different from the example.

**Comment by indiesquidge** [comment]
No problem, just thought I would ask. Still love the color scheme as it is!
