### ISSUE TITLE
Vim using iTerm2 base16 theme, not the one specified in vimrc

### ISSUE THREAD

**Issue by yoaquim** [chriskempson/base16-vim#64]
Vim is using the iTerm2 base16 themes, not the ones I specify in my .vimrc file.

I am using console vim.

I set up base16-shell and all is working as it should, just that it's not picking up the scheme I specify.

I'm using Pathogen, and found https://github.com/tpope/vim-pathogen/issues/57. 

Could it be that all color scripts need to sit at the root of `base16-vim`, not in `base16-vim/colors`?

Do I always have to specify the scheme I'll use with iTerm in the bash16-shell fix? As in, if I import mocha to iTerm, do I need to specify the mocha theme in the bash16-shell alias in my .bash_profile?

**Comment by chriskempson** [comment]
Console Vim can only use the colours available in the console. Therefore if your console Vim theme is different to your terminal's theme you won't see any difference.

**Comment by yoaquim** [comment]
So if I wanna change my vim theme, I have to change my terminal theme?

In other words, I change my color scheme through iTerm2/bash16-shell, not vim?

**Comment by chriskempson** [comment]
Yes, that's how it works for console Vim.

**Comment by yoaquim** [comment]
Thanks for the clarification! Never noticed, but I have always had my term scheme match vim!
