### ISSUE TITLE
Colors don't display in vim

### ISSUE THREAD

**Issue by Dbz** [chriskempson/base16-vim#70]
Hello, 

I am running OSX 10.9.5, Iterm2, and oh-my-zsh. I have followed all of the directions, and running ./colortest shows that I have properly installed colors. However, when I open a file in vim the colors do not show up, and everything is grey. There is no highlighting. Does anyone know what might be wrong?

**Comment by Dieterbe** [comment]
try these commands:
```
set background=dark
colorscheme base16-default
syntax on
```

the former two are from the readme and are probably obvious. the 3rd is the vim way to enable syntax highlighting for a file. make sure vim is able to do syntax highlighting no matter if you're customizing the colors or not, using the last command.

**Comment by Dbz** [comment]
Thank you @Dieterbe! That worked! I got some errors when I tried to source my `.vimrc` file. Off the top of your head, do you know why that might be? Thank you so much for the help you've given me. I greatly appreciate it.

    ➜  ~  source .vimrc
    .vimrc:4: no such file or directory:  set the runtime path to include Vundle and initialize\nset rtp+=~/.vim/bundle/Vundle.vim\ncall vundle#begin()\n\n\nset term=screen-256color\nset t_Co=256\nset background=dark\nlet base16colorspace=256
    .vimrc:13: command not found: syntax
    .vimrc:14: command not found: colorscheme
    .vimrc:19: command not found: Plugin
    .vimrc:20: command not found: Plugin
    .vimrc:22: command not found:  All of your Plugins must be added before the following line\ncall vundle#end()
    .vimrc:24: command not found: filetype
    .vimrc:26: command not found: filetype plugin on\n
    .vimrc:28: command not found:  Brief help\n
    .vimrc:30: command not found:  :PluginInstall    - installs plugins; append  to update or just :PluginUpdate\n
    .vimrc:31: command not found: append
    .vimrc:32: command not found:  :PluginClean      - confirms removal of unused plugins; append  to auto-approve removal\n
