### ISSUE TITLE
Doesn't work in XFCE terminal

### ISSUE THREAD

**Issue by yaabdalla** [chriskempson/base16-vim#72]
I followed [these instructions](https://github.com/chriskempson/base16-xfce4-terminal) to get base16-eighties working in my XFCE4 terminal. However, after following the instructions for base16-vim, my vim still isn't recognizing the colorscheme. Instead, I'm getting something like this: ![this](http://i.imgur.com/sByRvo6.png).
![](http://i.imgur.com/TY9OXMG.png)
Any help?

**Comment by chriskempson** [comment]
As far as I can tell that it working 😉
