### ISSUE TITLE
Colors not showing up right with iTerm2 + vim

### ISSUE THREAD

**Issue by toogy** [chriskempson/base16-vim#73]
Colors are not showing up right within vim using iTerm2.
It works perfectly on my Arch Linux laptop but not on my macbook. See:

<img width="832" alt="screen shot 2015-10-15 at 12 04 00 am" src="https://cloud.githubusercontent.com/assets/694873/10506810/77cfdf7c-72d0-11e5-9a32-e13c1119782c.png">

I do have 

```vim
set background=dark
let base16colorspace=256
colorscheme base16-ocean
```

in my .vimrc.

I don't understand where this strange color is coming from.
My iTerm2 is also configured with base16-ocean.
Everything works fine outside vim.

**Comment by tkonolige** [comment]
Have you tried removing `let base16colorspace=256`

**Comment by toogy** [comment]
@tkonolige oh yes sorry, i forgot to mention: i did exactly that and it fixed it
