### ISSUE TITLE
Always the same colorscheme as bash

### ISSUE THREAD

**Issue by prcastro** [chriskempson/base16-vim#74]
I'm having the following problem: whatever scheme I choose for my Shell, vim also uses it (despite any colorscheme command I throw at it).

Using bash on gnome-terminal

**Comment by bswinnerton** [comment]
Seeing a similar issue when using base16-shell.

It'd be nice to be able to use Tmux with vim in one colorscheme, but the other tmux panes in another colorscheme.

**Comment by nawendt** [comment]
I can also verify that when my shell is set using base16-shell, Vim uses the same color scheme as was set in the shell. I am using Gnome Terminal 2.31.3 on RHEL6 with tcsh as the default shell.

**Comment by joerideg** [comment]
Same here for gnome-terminal and xterm both on tmux and without.

**Comment by chriskempson** [comment]
That's how it is supposed to work I'm afraid, in non-GUI Vim it is your terminal that defines the colours Vim uses.
