### ISSUE TITLE
Cannot compatible with PuTTY and MinTTY at the same time

### ISSUE THREAD

**Issue by NoAnyLove** [chriskempson/base16-vim#81]
Here is a tricky problem. For some reason, I use PuTTY and MinTTY at the same time. The problem is, when I use MinTTY, I have to set `let base16colorspace=256` to get the correct line number color, and when in PuTTY, I should disable the `let base16colorspace=256` option for the same reason. So I have to change the .vimrc again and agian whenever I switch the tools.

Is there any method to solve this problem?

**Comment by christianbundy** [comment]
Set an environment variable through your client, and read it from your .vimrc?
