### ISSUE TITLE
Colours not loading/working

### ISSUE THREAD

**Issue by teaandcrumpet** [chriskempson/base16-vim#83]
I've tried everything to no avail. For some reason the colors aren't working withing vim, I've installed base16 shell, iTerm and Vim.

![screen shot 2016-02-25 at 12 13 57](https://cloud.githubusercontent.com/assets/17473301/13319584/9ebb9a88-dbba-11e5-9005-08a71fe89c45.png)
![screen shot 2016-02-25 at 12 15 18](https://cloud.githubusercontent.com/assets/17473301/13319586/9ebd7ec0-dbba-11e5-84c9-e869691985ae.png)
![screen shot 2016-02-25 at 11 55 58](https://cloud.githubusercontent.com/assets/17473301/13319585/9ebcf1bc-dbba-11e5-8b4a-f891ae54df92.png)

My .bashrc

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

BASE16_SHELL="$HOME/.config/base16-shell/base16-default.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

and my .bash_profile

BASE16_SHELL="$HOME/.config/base16-shell/base16-default.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

I've tried everything, removing then testing etc. When I run :scriptnames I can see that the theme is being loaded but the syntax highlighting is just not having it.

**Comment by etiennebatise** [comment]
Ok, what you have done so far is installing the base16 themes for your terminal, but not for vim. Vim and, in your case, iTerm don't share the same configuration files. Therefore, you also have to install the base16 package for Vim. 

Everything it detailed [here](https://github.com/chriskempson/base16-vim#vundle)

Also, for future issues, I encourage you to use github markdown syntax, especially when pasting code. That way, your reports will be a lot more readable. Ex: `export VARIABLE="foo"`
