### ISSUE TITLE
Atelier Cave?

### ISSUE THREAD

**Issue by thegranddesign** [chriskempson/base16-vim#84]
Atelier Cave has been added to the site, but not to this repo.  Is there a reason for that?  Does it need a PR?

**Comment by xaviervalarino** [comment]
@thegranddesign checkout my comment in [Issue #56 of Base16-Shell](https://github.com/chriskempson/base16-shell/issues/56#issuecomment-218909071)

You can get Atelier Cave by building it with a forked version of Base16 Builder—the current one is broken.That should create the vim file for _Atelier Cave_ (although I have been having trouble getting the built vim colorschemes to work, personally)

**Comment by chriskempson** [comment]
Fixed, sorry!
