### ISSUE TITLE
recurring issue on base16colorspace=256

### ISSUE THREAD

**Issue by aviator24** [chriskempson/base16-vim#86]
I saw lots of thread about wrong vim color, and most of all is resolved with base16colorspace=256 in .vimrc.
Not for me!

the colors seems wrong as seen in below.

![screenshot from 2016-04-28 23-34-52](https://cloud.githubusercontent.com/assets/13713687/14889500/fd1e335e-0d99-11e6-864a-0d907670a263.png)

I'm running in ubuntu 16.04 LTS.
I downloaded base16-shell and added base16 vim plugin also.
echo $TERM says I'm using xterm-256color.

In my .vimrc
let base16colorspace=256
colorscheme base16-default

In my .bashrc
BASE16_SHELL="$HOME/.config/base16-shell/base16-default.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

colortest script in base16-shell works fine.
I think I have done all things right... what's the problem?

**Comment by chriskempson** [comment]
Those colours look fine to me?

**Comment by aviator24** [comment]
I thought that those colours were incorrect because they were different with what I had in my original laptop. Probably something had gone wrong with it and I actually used non-base16 colours while thinking I did. Sorry for confusions, anyway.
