### ISSUE TITLE
hlsearch color (orange) for solarized dark

### ISSUE THREAD

**Issue by aphecetche** [chriskempson/base16-vim#87]
Hi,

I find that in my setup (iTerm 2.9.20160426, terminal neovim) orange of the hlsearch for solarized dark to be quite inconvenient (as the search term itself is light gray and so not much visible), see attached screenshot. 

First, is it normal or is my setup wrong somehow (I did use the colortest program and all seems fine in that respect) ? 

If it is normal, what's the more painless route to change that colour to my liking ?

Thanks,
<img width="730" alt="capture d ecran 2016-05-02 a 22 51 08" src="https://cloud.githubusercontent.com/assets/1566009/14967675/dae1f0e2-10b8-11e6-8b78-a279337772a4.png">

**Comment by chriskempson** [comment]
Should be a case of changing this line https://github.com/chriskempson/base16-vim/blob/master/templates/default.mustache#L103 to a colour of your liking.
