### ISSUE TITLE
Differences between base16-tomorrow and classic tomorrow themes

### ISSUE THREAD

**Issue by etiennebatise** [chriskempson/base16-vim#90]
Hi, 

I've switched few days ago from the [classic](https://github.com/chriskempson/tomorrow-theme) Tomorrow theme  to the [base16](https://github.com/chriskempson/base16-vim) one in my vim configuration. I've only noticed a few differences for the moment. You can see them in the following pictures:

  *  The classical theme (which I prefer): 
![screenshot_20160520_210724](https://cloud.githubusercontent.com/assets/5644956/15439044/5face01a-1ecf-11e6-8e51-4f3b2a892eef.png)

  * The second one being the base16 one
![screenshot_20160520_210654](https://cloud.githubusercontent.com/assets/5644956/15439045/650d1070-1ecf-11e6-94bf-7f030e62e344.png)

As I can't stand this coloured line number column or those grey folds, I have already made few fixes on my local install. I have updated the following objects : 
  * `LineNR`
  * `CursorLineNR`
  * `StatusLine`
  * `Folded` 

But I have not been able to make the "*Author*" and "*Source*" purple again.
 
Maybe I could make a pull request ?

**Comment by etiennebatise** [comment]
Also, the overall tone of the colours is a bit too light in the base16 theme. So, it is really hard to see in visual selection. On this image, left is *classic*, right is *base16*
![screenshot_20160520_225329](https://cloud.githubusercontent.com/assets/5644956/15441907/fe7a47a6-1edd-11e6-8b0a-333371499eba.png)

Not very representative in this image but all those comments in grey (on the right one) are really hard to read compared to those on the left.

**Comment by chriskempson** [comment]
The theme was a complete rewrite so there are differences. Base16 Tomorrow is just base16 with Tomorrow theme colours. If you prefer Tomorrow then you can still use it 👍
