### ISSUE TITLE
Unknown function issue using Neovim

### ISSUE THREAD

**Issue by tarebyte** [chriskempson/base16-vim#92]
Hi @chriskempson 👋 

I'm a user of Neovim, and I keep getting this error when I boot up after the latest update to base16-vim.

```
Error detected while processing /Users/tarebyte/.dotfiles/nvim/nvim.symlink/bundle/base16-vim/colors/base16-ocean.vim:
line  268:
E130: Unknown function: <sid>gui
line  269:
E130: Unknown function: <sid>cterm
Press ENTER or type command to continue
```

Looks like these two lines here: https://github.com/chriskempson/base16-vim/blob/master/colors/base16-ocean.vim#L268-L269

Not sure what to make of this, if you point me in the right direction I'd be more than happy to make a patch to fix this issue.

Or if this is a Neovim issue, feel free to close.

Thanks!

**Comment by tarebyte** [comment]
Ok so real quick update, I commented those two lines out and everything seems to be working ok. Honesty I don't know enough vimscript to know exactly what I'm doing though.

**Comment by quanganhdo** [comment]
Same problem here with vim & base16-eighties. Commenting out those lines worked for me.

**Comment by oryband** [comment]
This happens in standard vim as well, not just neo vim.

**Comment by oryband** [comment]
I've tracked the commit responsible for this bug: https://github.com/chriskempson/base16-vim/commit/701117e91e3ee20cb27b8da1d7d149e74c023746

**Comment by oryband** [comment]
This is odd. The commit is from 2013. How come the issue only appeared now?

**Comment by xguerin** [comment]
Ditto with vim & base16-eighties. Removing the two lines pertaining to undefined functions solves the issue.

**Comment by rslindee** [comment]
Having the same issue with base16-eighties. Commenting out the aforementioned lines removes the warnings.

**Comment by rfc1459** [comment]
Actually, 9daeb99 is the root cause: the definitions of `s:gui` and `s:cterm` have been removed in that commit, so (Neo)vim is complaining loudly that the functions being deleted do not exist.

It's safe to comment out (or delete) the offending lines until this issue gets fixed.

**Comment by chriskempson** [comment]
Just fixed sorry.
