### ISSUE TITLE
Can't change background color

### ISSUE THREAD

**Issue by adriaanzon** [chriskempson/base16-vim#93]
I used to be able to toggle the background color with `set background=light` and `set background=dark`, but since the last few updates that doesn't work anymore. The background stays dark and the rest of the colors change to a different color that aren't part of the color scheme.

Is this behavior intended?

I'm using base16-ocean, but I think it happens with every color scheme.

**Comment by chriskempson** [comment]
This is the new intended behaviour and is a result of the change described here: https://github.com/chriskempson/base16/issues/42

**Comment by CaioBianchi** [comment]
I'm having the same issue, and I *am* using the light variant.

**Comment by CaioBianchi** [comment]
![screen shot 2016-06-29 at 2 04 33 pm](https://cloud.githubusercontent.com/assets/681326/16463142/6d0f21f8-3e02-11e6-8453-0b414af3b2d4.png)

**Comment by chriskempson** [comment]
Vim colour schemes can't change the colour of your terminal. They only chance the colour of Vim GUI.

**Comment by CaioBianchi** [comment]
What?! **All** other colorschemes I have installed will keep the default background, only this one won't.
My terminal is at bottom right. This colorscheme reverses the light background (if the background option isn't set, it should default to light).
