### ISSUE TITLE
Cannot find color scheme 'base16-default' / No plugin folder

### ISSUE THREAD

**Issue by yoaquim** [chriskempson/base16-vim#94]
Vim can't seem to find the base-16-default colorscheme, even when everything else is setup correctly.

Noticed there's no `plugin` dir in the repo, while all my other vim plugins do have one (I use Pathogen).

I believe Pathogen looks at the `plugin` dir to gather what it needs, and I can confirm that when manually creating said dir and copying `base16-default-dark` (and light, but prob only need just one file) to this dir, it all seems to work.

I'm even able to change colors (via base16 for iTerm2 w/ base16 shell-fix) and it all works.

Thoughts?

**Comment by frenchja** [comment]
Since the latest commits, it looks like you have to manually specify whether it is a light or dark scheme:

```vim
colorscheme base16-default-dark
```

**Comment by yoaquim** [comment]
ah, makes sense. had not caught that!

thanks! 👍 

can confirm this works for me

**Comment by killtheliterate** [comment]
Curious about the reason for this. I frequently flipped between light and dark with `:set background=light` using the default scheme.

**Comment by chriskempson** [comment]
https://github.com/chriskempson/base16/issues/42#issue-162759173

**Comment by diegodesouza** [comment]
So I'm trying to place this `colorscheme base16-default-dark` in `vimrc` but still getting `E185: Cannot find color scheme 'base16-default-dark'` if I set the color `:colorscheme base16-default-dark` inside of vim` them it picks up. If I close the window then this setting goes away.

**Comment by pavilion** [comment]
@diegodesouza Im having the same problem! How did you fix it?

**Comment by eggbit** [comment]
@diegodesouza Having this exact same problem. Setting it in `.vimrc` just spits out an error.

**Comment by pavilion** [comment]
@eggbit Insert the following code in the following order:

1. 
`set background=dark                                                                                                                                        let base16colorspace=256                                                                                                                                    set termguicolors `

2.
`Plug 'chriskempson/base16-vim'`

3. (*optional for airline_theme)
`" vim-airline
let g:airline_theme = 'base16'
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tagbar#enabled = 1
let g:airline_skip_empty_sections = 1
`
4. (*select your color)
`colorscheme base16-default-dark`

If this does not work, change 2 step to including the color in your vim's color folder.

**Comment by salmanwaheed** [comment]
use without `light` or `dark` background in **.vimrc:** `colorscheme base16-onedark` since we are already used `background=dark` somewhere in the `.vimrc` file

**Comment by Avishayy** [comment]
For those that have this error, make sure the `colorscheme` line is placed after your plugins were loaded.
e.g. with Plugged, place `colorscheme base16-default-dark` below `plug#end()`
