### ISSUE TITLE
Can't use in Vim?

### ISSUE THREAD

**Issue by hristod** [chriskempson/base16-vim#98]
Hey!

I've got these two lines in my .vimrc:

Plug 'chriskempson/base16-vim'
colorscheme base16-default

but when I start Vim it says "Cannot find theme "base16-default"

**Comment by lfilho** [comment]
Did you call the command to install it?

**Comment by hristod** [comment]
It seems it's a problem with my .vimrc. Sorry for the issue!

**Comment by poliquin** [comment]
I was using the same setup, but `colorscheme base16-default` no longer works after running `PlugUpdate`.

I guess it's now necessary to specify dark/light variant as part of the colorscheme name?:

```vim
colorscheme base16-default-dark
```

**Comment by pruett** [comment]
I'm experiencing the same as @poliquin but `colorscheme base16-default-light` seems to produce an undesired color scheme.

**Comment by chriskempson** [comment]
@poliquin That's correct (see: https://github.com/chriskempson/base16/issues/42).
